name: tmsi
channels:
- tstenner
- conda-forge
dependencies:
- python=3.8
- liblsl
- pylsl
- ipython
- mne=0.23
- pyqtgraph=0.11
- pyside2=5.15
- backcall=0.2
- cloudpickle=2.0
- colorama=0.4
- cycler=0.10
- pip
- decorator=5.1
- entrypoints=0.3
- jedi=0.18
- kiwisolver=1.3
- nest-asyncio=1.5
- parso=0.8
- pexpect=4.8
- pickleshare=0.7
- pillow=8.3
- prompt-toolkit=3.0
- ptyprocess=0.7
- pygments=2.10
- pyparsing=2.4
- python-dateutil=2.8
- pytz=2021.3
- pyxdf=1.16
- pyzmq=22.3
- six=1.16
- tornado=6.1
- traitlets=4.3
- wcwidth=0.2
- wurlitzer=3.0
- pyserial
- edflib-python
